subjectId = 'Pilot1';

inputFolder = [subjectId,'/','MAT'];
outputFolder=[subjectId];

markerSet = {'FCC','TAM','FM1','FM2','FM5','FAL'};
markerLeftFootPrefix = 'L_';
markerRightFootPrefix = 'R_';

bodyWeight = 76*9.81;

inputC3DFiles = { 'test0001_done.c3d',...
                  'test0002_done.c3d',...
                  'test0003_done.c3d',...
                   'test0004_done.c3d',...
                   'test0005_done.c3d',...
                   'test0006_done.c3d',...                  
                  'test0007_done.c3d',...
                  'test0008_done.c3d',...
                  'test0009_done.c3d',...
                   'test0010_done.c3d',...        
                   'test0011_done.c3d',...
                   'test0012_done.c3d',...
                  'test0013_done.c3d',...
                  'test0014_done.c3d',...                  
                  'test0015_done.c3d',...
                   'test0016_done.c3d',...
                   'test0017_done.c3d',...
                   'test0018_done.c3d',...
                  'test0019_done.c3d',...
                  'test0020_done.c3d'};

                
                
withShoes = zeros(length(inputC3DFiles),1);
withShoes(13:end,1)=1;                
                
trialIsValid = ones(length(inputC3DFiles),1);
trialIsValid(18,1)=0;
trialIsValid(19,1)=0;

updateFootFrames = zeros(length(inputC3DFiles),3);
% update flag (0/1), index of c3d file to use, index of time sample to use
updateFootFrames(1,:)  = [1,1,1];
updateFootFrames(13,:) = [1,13,1];

processedOutliers = [7,11,10];