subjectId = 'Pilot1';

inputFolder = [subjectId,'/','MAT'];
outputFolder=[subjectId];

markerSet = {'FCC','TAM','FM1','FM2','FM5','FAL'};
markerLeftFootPrefix = 'L_';
markerRightFootPrefix = 'R_';


inputC3DFiles = { 'test0001_done.c3d',...
                  'test0002_done.c3d',...
                  'test0003_done.c3d',...
                  'test0004_done.c3d',...
                  'test0005_done.c3d',...
                  'test0006_done.c3d',...                  
                  'test0007_done.c3d',...
                  'test0008_done.c3d',...
                  'test0009_done.c3d',...
                  'test0010_done.c3d',...        
                  'test0011_done.c3d',...
                  'test0012_done.c3d',...
                  'test0013_done.c3d',...
                  'test0014_done.c3d',...                  
                  'test0015_done.c3d',...
                  'test0016_done.c3d',...
                  'test0017_done.c3d',...
                  'test0018_done.c3d',...
                  'test0019_done.c3d',...
                  'test0020_done.c3d'};

inputC3DOffsetFile   = 'test0001_done.c3d'
inputOffsetTimeIndex = 1;

