function figH = plotGroupAntsOnALog(figH, subPlotVec,...
                                      group,...
                                      summaryData,...
                                      xPositionData, xPositionVerticalLine,...
                                      yLabelOffset,...
                                      flag_plotVerticalLine)


figure(figH);
if(length(subPlotVec) == 3)
  subplot(subPlotVec(1,1),subPlotVec(1,2),subPlotVec(1,3));
end  
if(length(subPlotVec) == 4)
  subplot('Position',subPlotVec);
end
% 
% summaryData = zeros(7,1);
% n = length(group.index);    
% for indexSubject = 1:1:length(subjectSummaryData)
%   if( any(group.index == indexSubject ) )
%     summaryData = summaryData ...
%       + subjectSummaryData(indexSubject).(summaryDataStructName)(:,indexTrial);
%   end
% end
% 
% summaryData = summaryData./n;



axisLim = axis;

xPosData = xPositionData;
xPosLine = xPositionVerticalLine;
if(flag_plotVerticalLine==1)
  dy = (axisLim(4)-axisLim(3))*0.05;
  plot([xPosLine;xPosLine],[axisLim(3)+dy;axisLim(4)-dy],...
        'Color',[1,1,1],'LineWidth',1);
  hold on;
  plot([xPosLine;xPosLine],[axisLim(3)+dy;axisLim(4)-dy],...
        'Color',[1,1,1].*0.75,'LineWidth',0.5);
  hold on;
end

figH = plotAntsOnALog(figH, subPlotVec,...
                xPosData,...
                summaryData(1,1),...
                summaryData(3,1),...
                summaryData(5,1),...
                summaryData(2,1),...
                summaryData(4,1),...
                [summaryData(6,1),summaryData(7,1)],...
                {'o','o'},[1,1,1; group.color],...
                0.33,group.color);
axis(axisLim);
yLabelPos = axisLim(3)+ yLabelOffset*(axisLim(4)-axisLim(3));

text( xPosData, yLabelPos, group.name,...
      'FontSize',8,'Interpreter','latex','HorizontalAlignment','center');  
    hold on;  